# Generated by Django 4.2 on 2025-07-28 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('asistencia_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('fecha_check_in', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Reservado', 'Reservado'), ('Asistió', 'Asistió'), ('Canceló', 'Canceló'), ('No se presentó', 'No se presentó')], default='Reservado', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriasGasto',
            fields=[
                ('categoria_gasto_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=100, unique=True)),
                ('tipo_gasto', models.CharField(choices=[('Fijo', 'Fijo'), ('Variable', 'Variable')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Clases',
            fields=[
                ('clase_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_clase', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('duracion_minutos_default', models.IntegerField(blank=True, null=True)),
                ('capacidad_maxima_default', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClasesProgramadas',
            fields=[
                ('clase_programada_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('fecha_hora_fin', models.DateTimeField()),
                ('sala_o_ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('capacidad_actual', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('Programada', 'Programada'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], default='Programada', max_length=50)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gym.clases')),
            ],
        ),
        migrations.CreateModel(
            name='Miembros',
            fields=[
                ('miembro_id', models.AutoField(help_text='ID único para cada miembro.', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('congelado', 'Congelado'), ('potencial', 'Potencial')], default='potencial', max_length=50)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=20, null=True)),
                ('notas_administrativas', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanesMembresia',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_plan', models.CharField(help_text='Nombre único del plan de membresía.', max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio del plan.', max_digits=10)),
                ('duracion_dias', models.IntegerField(blank=True, help_text='Duración en días para planes de período fijo (ej. 30, 365).', null=True)),
                ('numero_clases', models.IntegerField(blank=True, help_text='Número de clases incluidas para planes tipo bono.', null=True)),
                ('tipo_plan', models.CharField(choices=[('Solo Pilates', 'Solo Pilates'), ('Solo Gimnasio', 'Solo Gimnasio'), ('Completo', 'Completo'), ('Bono', 'Bono')], max_length=50)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el plan está actualmente ofrecido.')),
            ],
        ),
        migrations.CreateModel(
            name='PreferenciasDefault',
            fields=[
                ('nombre_preferencia', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('valor_default', models.TextField()),
                ('tipo_dato', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RolesPersonal',
            fields=[
                ('rol_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=100, unique=True)),
                ('descripcion_rol', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuscripcionesMiembro',
            fields=[
                ('suscripcion_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada'), ('futura', 'Futura')], max_length=50)),
                ('precio_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('clases_restantes', models.IntegerField(blank=True, help_text='Créditos restantes para planes tipo bono.', null=True)),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.miembros')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gym.planesmembresia')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('personal_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_contratacion', models.DateField()),
                ('especialidades', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.rolespersonal')),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('pago_id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(choices=[('Tarjeta de Crédito', 'Tarjeta de Crédito'), ('Transferencia', 'Transferencia'), ('Efectivo', 'Efectivo'), ('Otro', 'Otro')], max_length=50)),
                ('concepto', models.CharField(max_length=255)),
                ('id_transaccion_externa', models.CharField(blank=True, max_length=255, null=True)),
                ('miembro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.miembros')),
                ('suscripcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.suscripcionesmiembro')),
            ],
        ),
        migrations.CreateModel(
            name='MetasMiembro',
            fields=[
                ('meta_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_meta', models.CharField(choices=[('Pérdida de peso', 'Pérdida de peso'), ('Ganancia muscular', 'Ganancia muscular'), ('Mejora de flexibilidad', 'Mejora de flexibilidad'), ('Aumento de resistencia', 'Aumento de resistencia'), ('Bienestar general', 'Bienestar general')], max_length=100)),
                ('valor_objetivo', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_objetivo', models.DateField(blank=True, null=True)),
                ('estado_meta', models.CharField(choices=[('Activa', 'Activa'), ('Alcanzada', 'Alcanzada'), ('Abandonada', 'Abandonada')], default='Activa', max_length=50)),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.miembros')),
            ],
        ),
        migrations.CreateModel(
            name='LogsEntrenamiento',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ejercicio', models.DateField()),
                ('nombre_ejercicio', models.CharField(max_length=100)),
                ('series', models.IntegerField(blank=True, null=True)),
                ('repeticiones', models.IntegerField(blank=True, null=True)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('duracion_segundos', models.IntegerField(blank=True, null=True)),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('notas_personales', models.TextField(blank=True, null=True)),
                ('asistencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.asistencia')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.miembros')),
            ],
        ),
        migrations.CreateModel(
            name='HorariosPersonal',
            fields=[
                ('horario_id', models.AutoField(primary_key=True, serialize=False)),
                ('inicio_turno', models.DateTimeField()),
                ('fin_turno', models.DateTimeField()),
                ('notas', models.TextField(blank=True, null=True)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.personal')),
            ],
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('gasto_id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_gasto', models.DateField()),
                ('proveedor', models.CharField(blank=True, max_length=150, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria_gasto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gym.categoriasgasto')),
                ('personal_id_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.personal')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackMiembro',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.IntegerField(help_text='Rating from 1 to 5')),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_feedback', models.DateTimeField(auto_now_add=True)),
                ('clase_programada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.clasesprogramadas')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.personal')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.miembros')),
            ],
        ),
        migrations.AddField(
            model_name='clasesprogramadas',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.personal'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='clase_programada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.clasesprogramadas'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='miembro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.miembros'),
        ),
        migrations.CreateModel(
            name='PreferenciasUsuarioOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_personalizado', models.TextField()),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.miembros')),
                ('nombre_preferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.preferenciasdefault')),
            ],
            options={
                'unique_together': {('miembro', 'nombre_preferencia')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('clase_programada', 'miembro')},
        ),
    ]
